### PR TITLE
RTRM: fix lmk permissions

### PR DESCRIPTION
**Pull request by luca020400**

### CODE REVIEW

**Comment by Pizza-Dox** [comment]
Thanks Luca, :) merged.
So these new permissions should allow the lmk r/w to work on CM12? If so thats awesome. If not i will look into a way to changing it somehow, via /data/local/tmp or whatnot.
Again thanks :+1:

**Comment by luca020400** [comment]
https://github.com/MotorolaMobilityLLC/system-core/commit/bacd21e6734ae626527e8a669fd555c4b4eeba16

**Comment by luca020400** [comment]
And you should join the irc channel :3
#titandev

**Comment by Pizza-Dox** [comment]
Ahh ok so they reverted that change, lovely, :D thanks, irc? heard of it alot, ill go ahead and join now, ill use "freenode" :) :+1:

**Pull request merged**
